### ISSUE TITLE
ng-sortable.js:84 Uncaught TypeError: Cannot read property

### ISSUE THREAD

**Issue by OktavianRS** [SortableJS/angular-legacy-sortablejs#14]
Error fires on drag event if one of these functions: `onStart(), onEnd(), onDrag()... etc.` was declared in ng-sortable configs.

This error is triggered because variable: `var source = getSource();` got undefined in function: `_emitEvent(evt)` file ng-sortable.js at line 79. 

My solution was: ng-sortable.js file, change function _emitEvent()
delete lines 84 and 85 so function now looks like: 
`
function _emitEvent(/**Event*/evt, /*Mixed*/item) {
 var name = 'on' + evt.type.charAt(0).toUpperCase() + evt.type.substr(1);
  var source = getSource();
   /* jshint expr:true */
   options[name] && options[name]({
    oldIndex: evt.oldIndex,
    newIndex: evt.newIndex
   });
}
`

**Comment by samjacobclift** [comment]
I had a similar error. Have you by any chance installed sortable.js with npm? There are some fixes in the master branch of sortable.js that are not published to npm. Try running your app with a copy of the latest sortable.js taken from master
