### ISSUE TITLE
Sortable error if $compileProvider.debugInfoEnabled(false)

### ISSUE THREAD

**Issue by lorenzodianni** [SortableJS/angular-legacy-sortablejs#18]
_emitEvent has an inner function getSource() that return null because ng-repeat regex doesn't match any childNodes on angular debug comments. So any event (onStart, onSort, etc...) doesn't work.

**Comment by aeharding** [comment]
I also see this. Did you find a suitable workaround?

**Comment by lorenzodianni** [comment]
Try to update the core library, it should be fixed

```shell
npm i sortablejs -S
```

**Comment by aeharding** [comment]
Awesome. Thanks, @lorenzodianni! Works for me. Should this issue be closed then?

**Comment by lorenzodianni** [comment]
@aeharding Great!

I think it could be closed ;)

**Comment by aeharding** [comment]
(Quick note though: I had to install the master branch in order to not get require('./Sortable') errors, see #20.)
