### ISSUE TITLE
Not available with npm install

### ISSUE THREAD

**Issue by koumatsumoto** [SortableJS/angular-legacy-sortablejs#20]
I installed this package with npm. `npm install -S angular-legacy-sortablejs`.
but it occurs error below.

```
Module not found: Error: Cannot resolve module 'angular-legacy-sortablejs' in /home/myproject/src/
```

May be because of `require('./Sortablejs')`

I think that published package to npm is older than github#master.
Please republish.

thanks.

**Comment by aeharding** [comment]
@RubaXa I'd love if this could be republished. Otherwise, it's currently unusable.

If you still need someone to help with the project, I'd be willing to help maintain it.

Thanks!

**Comment by samjacobclift** [comment]
@RubaXa do I need access to the npm package to be able to publish a new version?

**Comment by samjacobclift** [comment]
published under new package name with latest commits
