### ISSUE TITLE
two elements sorting problem

### ISSUE THREAD

**Issue by despagito** [SortableJS/angular-legacy-sortablejs#23]
When there're two elements,then after three times of exchanging, there will be a bug:
```
angular.min.js:103 Error: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
    at Comment.<anonymous> (jquery-1.8.2.min.js:2)
    at init.domManip (jquery-1.8.2.min.js:2)
    at init.after (jquery-1.8.2.min.js:2)
    at Object.enter (angular.min.js:176)
    at Object.move (angular.min.js:176)
    at angular.min.js:235
    at Object.fn (angular.min.js:122)
    at l.$digest (angular.min.js:123)
    at l.$apply (angular.min.js:126)
    at Sortable.onEnd (ng-sortable.js:141)
```
and in the first of exchanging, the callback parameter `evt` return the wrong order in `evt.models`.

**Comment by celsomtrindade** [comment]
I'm running into the same error, but this happens when I try to use the put/pull method defined within the group params when working with nested sorting.

For example, when I have a list like this:

    vm.list = [
        {id: 1, name: 'Name of item 1',
            gallery: [
                {id: 1, name: 'Name of image 1'},
                {id: 2, name: 'Name of image 2'},
                {id: 3, name: 'Name of image 3'}
            ]
        },
        {id: 2, name: 'Name of item 2', 
            gallery: [
                {id: 1, name: 'Name of image 1'},
                {id: 2, name: 'Name of image 2'},
            ]
        },
        {id: 3, name: 'Name of item 3', gallery: []}
    ];

And use it like this:

    <ul ng-sortable>
        <li ng-repeat="item in vm.list track by item.id">
            <p>{{item.name}}</p>
            <ul ng-sortable="{group: {name:'child', put: true, pull:true} }">
                <li ng-repeat="gallery in item.gallery track by gallery.id">
                    <p>{{gallery.nome}}</p>
                </li>
            </ul> 
        </li>
    </ul>

I also tried to define the nested sortable item as follow:

    <ul ng-sortable="{group: {name:'child{{item.id}}', put: true, pull:true} }">

    //or
    <ul ng-sortable="{group: {name:'child{{item.id}}', put: 'child{{item.id}}', pull:true} }">

Both give me the same end result, wich is the same error as you. The console creates a reference to this line 118 and 172:

    115 if (evt.clone) {
    116     removed = angular.copy(removed);
    117     prevItems.splice(Sortable.utils.index(evt.clone, sortable.options.draggable), 0, prevItems.splice(oldIndex, 1)[0]);
    118     evt.from.removeChild(evt.clone);
    119 }
    [...]
    171 onAdd: function (/**Event*/evt) {
    172     _sync(evt);
    173     _emitEvent(evt, removed);
    174     scope.$apply();
    175 },

**Comment by samjacobclift** [comment]
fixed please pull latest

**Comment by samjacobclift** [comment]
reopen the issue if its not :)
