### ISSUE TITLE
Update npm

### ISSUE THREAD

**Issue by dan-leech** [SortableJS/angular-legacy-sortablejs#24]
Update npm, please.
You have `require('./Sortable')` instead `require('sortablejs')` there

**Comment by marcbachmann** [comment]
@RubaXa The version on npm is currently unusable. I'm almost at the point of publishing this lib to npm with a different name just to fix it.

**Comment by roelbarreto** [comment]
hmmm when it will be available via npm? like the current npm lib is broken

**Comment by samjacobclift** [comment]
I could fork this repo and then publish that to npm at least then we could push updates out. Wdwt the package name should be?

**Comment by samjacobclift** [comment]
maybe it can be the same name just under my username

**Comment by samjacobclift** [comment]
maybe make the name quite specific `angular-legacy-sortablejs-maintained` then there is no confusion there

**Comment by samjacobclift** [comment]
published under this [package](https://www.npmjs.com/package/angular-legacy-sortablejs-maintained)

**Comment by samjacobclift** [comment]
and added an example app that uses that package let me know if any bugs, we can close this issue if people are happy now
