### ISSUE TITLE
Bower install

### ISSUE THREAD

**Issue by mudin3i** [SortableJS/angular-legacy-sortablejs#3]
It would be great if we can add using bower!

**Comment by octavioamu** [comment]
Had submitted a PR to add the bower file #10

**Comment by octavioamu** [comment]
@Mudin  sortablejs dependency is wrong too and "main" has all the plugins so there is a quick solution
Run a `bower install sortablejs --save`
go to your bower.json project and add this overrides 

`
  "overrides": {
    "Sortable": {
      "main": [
        "Sortable.js",
        "ng-sortable.js"
      ]
    }
  },
`
That will let you use the angular version with the plugin dependencies without the meter and all the others.

**Comment by mudin3i** [comment]
@octavioamu That's awesome! very appreciate it. 
Thank you very much

**Comment by MattBroach** [comment]
Just a heads up if anybody comes across this later: it looks like the ng-sortable.js has been removed from the main sortablejs bower package.  It has to be installed separately now.
