### ISSUE TITLE
ng-repeat isn't actualized after using ng-sortable

### ISSUE THREAD

**Issue by clementbirkle** [SortableJS/angular-legacy-sortablejs#30]
ng-repeat isn't actualized after using ng-sortable,

For exemple:
```
 <tbody ng-sortable="vm.sortableConfig" ng-repeat="(key, value) in array">
    <tr>{{key}}</tr>
</tbody>
```

The result before using sortable:
1
2
3

The result for exemple after using sortable:
2
1
3

The result wanted after using sortable:
1
2
3

Apparently, ng-repeat isn't informed from ng-sortable. The key from ng-repeat isn't updated.
Have you a solution for this problem ? Thank you in advance.

**Comment by samjacobclift** [comment]
you need to use `<ul>` and `<li>` elements as documented in [sortable](https://github.com/RubaXa/Sortable/)

**Comment by samjacobclift** [comment]
does that help?

**Comment by clementbirkle** [comment]
I solved the problem. Actually, It wasn't a SortableJs mistake but was my code... 

I used key in ng-class: ng-class="{'group-{{key}}': true}" => it was false. Then, i put it directly in class and now it works well !

**Comment by samjacobclift** [comment]
nice sounds good!
