### ISSUE TITLE
support sortablejs 1.6.0

### ISSUE THREAD

**Issue by ddankwerth** [SortableJS/angular-legacy-sortablejs#32]
Hi 

Sortablejs released version 1.6.0 which fixes a memory leak, however, the angularjs version requires v1.5.x 

When are you planning on releasing a version that works with 1.6.0 ? 

Thanks

**Comment by samjacobclift** [comment]
I attempted to upgrade an app to use 1.6 however there where a couple of issues (not sure they are problems with the integration or how we used sortable)

SortableJS is just a peer dependancy so you can use whatever version of SortableJS you like (just add it to you package.json) however I can't confirm 1.6 works 

You could try out using sortableJS in your app and submit feedback here to help try and support it

**Comment by ddankwerth** [comment]
Thanks for the quick response, I've now upgraded sortablejs and will keep an eye on problems ...

**Comment by samjacobclift** [comment]
Please do, it seemed to be drag handles that caused issues for me.

**Comment by FrEaKmAn** [comment]
I have been using it with latest version (1.6.1) and no problems so far. Should be safe to upgrade dependency version.

**Comment by nicolaslt** [comment]
Current dependency declaration does raise issues with npm shrinkwrap. Our team need to manually edit our shrinkwrap/package-lock file to force SortableJS version higher than 1.5.X; and remember to do so every time we take an action that re-generates this file.

If SortableJS is to be a peer depedency, could it be removed from your package.json's declared dependencies?

**Comment by samjacobclift** [comment]
@nicolaslt sure if you would like to create a PR I can merge it and make a new version

**Comment by samjacobclift** [comment]
@nicolaslt merged and push a version to npm (v0.6.1) let me know if there are more issues
