### ISSUE TITLE
error when change browser tab and this problem only happens with Chrome

### ISSUE THREAD

**Issue by josepfdc** [SortableJS/angular-legacy-sortablejs#33]
the following error message appears in the console :

**Error in event handler for runtime.onMessage: TypeError: Cannot read property 'val' of undefined
    at Object.cipEvents.triggerActivatedTab (chrome-extension://oakpnnaknlicjghpchokjoelhfjnmhcd/rdmchrome.js:2313:14)
    at chrome-extension://oakpnnaknlicjghpchokjoelhfjnmhcd/rdmchrome.js:61:14**

this error appear when I change of browser tab and only happens in Chrome browser.

I am using sortable with angular

"angular": "1.6.4",
"sortablejs": "^1.5.1"
 "angular-legacy-sortablejs-maintained": "^0.5.2"

**Comment by samjacobclift** [comment]
this seems to be caused but a chrome extension? not too sure tbh
