### ISSUE TITLE
Update to 1.7.0

### ISSUE THREAD

**Issue by vpapadopou** [SortableJS/angular-legacy-sortablejs#39]
Latest chrome update breaks sortable 1.6.0 so we need to update to 1.7.0 to use it again. 

Ref: https://github.com/RubaXa/Sortable/issues/1213

In firefox the old version works as expected.

**Comment by samjacobclift** [comment]
See https://github.com/SortableJS/angular-legacy-sortablejs/issues/32#issuecomment-349281668 I’ll remove the peer dependency not sure 1.7 will work with 1.6 though

**Comment by samjacobclift** [comment]
@vpapadopou we updated sortableJS to be a lenient peer dependency so now you should be able to use any version of sortableJS you like published to NPM as v0.6.1

**Comment by samjacobclift** [comment]
Going to close this issue can reopen if there are more issues
