### ISSUE TITLE
Doesn't work with ng-if

### ISSUE THREAD

**Issue by adamreisnz** [SortableJS/angular-legacy-sortablejs#4]
If applying `ng-sortable` on an element which also has `ng-if`, the plugin causes an error:

```
Cannot create property 'stack' on string 'Sortable: `el` must be HTMLElement, and not [object Comment]'
```

I presume because it's getting the comment node that Angular inserts for the `ng-if` handling.

**Comment by willjk** [comment]
this might be fixed with a compile postLink or changing the priority of the directive. Haven't tried but give it a shot

**Comment by adamreisnz** [comment]
Thanks for the suggestion. I have refactored my code to not have the `ng-if` on the sortable directive anymore, which seemed like the simplest solution.

**Comment by samjacobclift** [comment]
'ng-if' creates a new scope in an angular templates perhaps it's best to use an 'ng-show' or use '$parent'

**Comment by RopoMen** [comment]
This does not work, gives error above if ngIf is false initially
```
<ul ng-sortable="sortConfig" ng-if="something">
  <li ng-repeat="item in items" ng-bind="item.name"></li>
</ul>
```
This works and is a workaround for issue.
```
<div ng-if="something">
  <ul ng-sortable="sortConfig">
    <li ng-repeat="item in items" ng-bind="item.name"></li>
  </ul>
</div>
```

"I presume because it's getting the comment node that Angular inserts for the ng-if handling." - yes.

ngSortable should require "ngIf" optionally and if ngIf is defined for the element, ngSortable should watch ngIf value and initialize it self when ngIf is true.

**Comment by samjacobclift** [comment]
see my previous comment the `ng-if` is creating a new scope to solve your issue you would need to have this code
```
<div ng-if="something">
  <ul ng-sortable="$parent.sortConfig">
    <li ng-repeat="item in items" ng-bind="item.name"></li>
  </ul>
</div>
```
