### ISSUE TITLE
Delayed drag instantly canceled on chrome mobile

### ISSUE THREAD

**Issue by oschlegel** [SortableJS/angular-legacy-sortablejs#41]
When the delay configuration is set to a value greater than zero, the _disableDelayedDrag function is called almost instantly after _prepareDragStart by a mousemove event. This causes  the drag and drop to be not useable.

This problem occurs in chrome on android.
Chrome version: 63.0.3239.11
Android version 8.0.0

**Comment by rainboxx** [comment]
We discovered that this behavior can be removed by setting the (undocumented) option `supportPointer` of [SortableJS](https://github.com/rubaxa/Sortable) to `false` for touch devices.

This issue can be closed.
