### ISSUE TITLE
TypeError: Sortable.create is not a function

### ISSUE THREAD

**Issue by samal-rasmussen** [SortableJS/angular-legacy-sortablejs#52]
angular-legacy-sortable imports sortablejs incorrectly after versions 1.10.0 of sortablejs, which leads to it not finding Sortablejs.create.

More info in this issue:
https://github.com/SortableJS/Sortable/issues/1728

**Comment by OzzieOrca** [comment]
I have a branch here if anyone's interested https://github.com/OzzieOrca/angular-legacy-sortablejs/tree/fix-sortablejs-import
```json
"angular-legacy-sortablejs-maintained": "https://github.com/OzzieOrca/angular-legacy-sortablejs#fix-sortablejs-import",
```
