### ISSUE TITLE
Buggy when filters are used in ng-repeat

### ISSUE THREAD

**Issue by adamreisnz** [SortableJS/angular-legacy-sortablejs#6]
Beware when using `event.model` if you have filters on your `ng-repeat` directive. SortableJS will report the _wrong_ item in `event.model`. You will need to find the correct item manually using the `event.oldIndex` and/or the `event.newIndex` properties.

Also beware that when using filters, the `event.models` array comes in the _old_ sort order, not the new one. Without using filters, the new sort order array is passed properly.

**Comment by thgoo** [comment]
In case anyone still has this issue, I get it working with a workaround.

Changed `var rhs = match[2];` by `var rhs = match[2].split(' | ')[0];` in "angular-legacy-sortable.js:66".

Got it working fine in my use case.
